### PR TITLE
fix(expo): make the config plugin idempotent

### LINKED ISSUE #747: [🐛] Prebuilds are polluting AndroidManifest with extra meta-data
### What happened?

Every prebuild of react-native through Expo adds to ``AndroidManifest.xml entries``
```
    <meta-data android:name="com.google.android.gms.ads.flag.OPTIMIZE_AD_LOADING" android:value="true" tools:replace="android:value"/>
    <meta-data android:name="com.google.android.gms.ads.flag.OPTIMIZE_INITIALIZATION" android:value="true" tools:replace="android:value"/>

```
I'm using expo 52.

I removed them, but this is what it looked like after a few builds:
Image

Regards :)

### Platforms

Only on Android

### React Native Info

```Shell
info Fetching system and libraries information...
System:
  OS: macOS 15.4.1
  CPU: (10) arm64 Apple M2 Pro
  Memory: 241.56 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 22.14.0
    path: ~/.nvm/versions/node/v22.14.0/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.nvm/versions/node/v22.14.0/bin/yarn
  npm:
    version: 11.2.0
    path: ~/.nvm/versions/node/v22.14.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/lib/ruby/gems/3.2.0/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.4
      - iOS 18.4
      - macOS 15.4
      - tvOS 18.4
      - visionOS 2.4
      - watchOS 11.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.23339.11.2421.12550806
  Xcode:
    version: 16.3/16E140
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.8.1
    path: /usr/bin/javac
  Ruby:
    version: 3.2.2
    path: /opt/homebrew/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 18.0.0
    wanted: ^18.0.0
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.9
    wanted: 0.76.9
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

info React Native v0.79.2 is now available (your project is running on v0.76.9).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.79.2
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.76.9&to=0.79.2
info For more info, check out "https://reactnative.dev/docs/upgrading?os=macos".
```

### Are your using Typescript?

- [x] My project is using Typescript

### package.json

```JSON
{
  "name": "appName",
  "version": "1.0.0",
  "main": "expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "1.23.1",
    "@react-native-community/netinfo": "11.4.1",
    "@react-native-firebase/analytics": "^21.2.0",
    "@react-native-firebase/app": "^21.2.0",
    "@react-navigation/elements": "^2.1.1",
    "@react-navigation/native": "^6.1.18",
    "@react-navigation/stack": "^6.4.1",
    "@reduxjs/toolkit": "^2.7.0",
    "@sentry/react-native": "^6.10.0",
    "axios": "^1.9.0",
    "dayjs": "^1.11.13",
    "expo": "~52.0.46",
    "expo-apple-authentication": "~7.1.3",
    "expo-application": "~6.0.2",
    "expo-build-properties": "~0.13.2",
    "expo-clipboard": "~7.0.1",
    "expo-constants": "~17.0.8",
    "expo-crypto": "~14.0.2",
    "expo-status-bar": "~2.0.1",
    "expo-tracking-transparency": "~5.1.1",
    "immer": "^10.1.1",
    "node-html-markdown": "^1.3.0",
    "onesignal-expo-plugin": "^2.0.3",
    "react": "18.3.1",
    "react-native": "0.76.9",
    "react-native-date-picker": "^5.0.7",
    "react-native-fbsdk-next": "^13.1.3",
    "react-native-gesture-handler": "~2.20.2",
    "react-native-google-mobile-ads": "^14.11.0",
    "react-native-kochava-tracker": "^2.8.2",
    "react-native-markdown-display": "^7.0.2",
    "react-native-onesignal": "^5.2.9",
    "react-native-safe-area-context": "4.12.0",
    "react-native-screens": "~4.4.0",
    "react-redux": "^9.2.0",
    "redux": "^4.2.1",
    "redux-devtools-expo-dev-plugin": "^1.0.0",
    "redux-saga": "^1.3.0",
    "symbol-observable": "^4.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.3.12",
    "@typescript-eslint/eslint-plugin": "^8.11.0",
    "@typescript-eslint/parser": "^8.11.0",
    "eslint": "^8.57.0",
    "eslint-config-expo": "~8.0.1",
    "eslint-plugin-react": "^7.37.2",
    "eslint-plugin-react-native": "^4.1.0",
    "eslint-plugin-simple-import-sort": "^12.1.1",
    "typescript": "~5.3.3"
  },
  "private": true
}
```

### app.json

```JSON
{
  "expo": {
    "name": "appname",
    "slug": "appname",
    "scheme": "appname",
    "version": "1.54",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "userInterfaceStyle": "light",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ed0924"
    },
    "notification": {
      "icon": "./assets/notification.png",
      "color": "#ed0924"
    },
    "ios": {
      "supportsTablet": false,
      "bundleIdentifier": "pl.appname.appname",
      "usesAppleSignIn": true,
      "googleServicesFile": "./GoogleService-Info.plist",
      "buildNumber": "102",
      "infoPlist": {
        "NSLocationWhenInUseUsageDescription": "Używamy lokalizacji w celu zapewnienia lepiej dopasowanych ofert.",
        "NSUserTrackingUsageDescription": "Dzięki temu będziemy mogli tworzyć spersonalizowane oferty oraz ulepszać funkcjonalność aplikacji.",
        "LSMinimumSystemVersion": "15.0",
        "LSApplicationCategoryType": "public.app-category.shopping",
        "NSAppTransportSecurity": {
          "NSAllowsArbitraryLoads": true
        },
        "SKAdNetworkItems": [
          {
            "SKAdNetworkIdentifier": "v9wttpbfk9.skadnetwork"
          },
          {
            "SKAdNetworkIdentifier": "n38lu8286q.skadnetwork"
          }
        ]
      },
      "appleTeamId": "8JW68V4W53"
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#ed0924"
      },
      "googleServicesFile": "./google-services.json",
      "package": "pl.appname.appname",
      "versionCode": 102,
      "permissions": [
        "com.google.android.gms.permission.AD_ID",
        "android.permission.INTERNET"
      ]
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "plugins": [
      [
        "expo-tracking-transparency",
        {
          "userTrackingPermission": "USER_TRACKING_PERMISSION"
        }
      ],
      [
        "onesignal-expo-plugin",
        {
          "mode": "production",
          "devTeam": "DEV_TEAM_ID",
          "iPhoneDeploymentTarget": "14.7",
          "smallIcons": [
            "./assets/notification.png"
          ],
          "largeIcons": [
            "./assets/notification_large.png"
          ],
          "smallIconAccentColor": "#ed0924"
        }
      ],
      [
        "react-native-fbsdk-next",
        {
          "appID": "APP_ID",
          "clientToken": "CLIENT_TOKEN",
          "displayName": "appname",
          "scheme": "fbAPP_ID",
          "advertiserIDCollectionEnabled": false,
          "autoLogAppEventsEnabled": true,
          "isAutoInitEnabled": true,
          "iosUserTrackingPermission": "USER_TRACKING_PERMISSION"
        }
      ],
      [
        "expo-apple-authentication"
      ],
      [
        "@sentry/react-native/expo",
        {
          "organization": "appname-sp-z-oo",
          "project": "appname",
          "url": "https://sentry.io/"
        }
      ],
      "@react-native-firebase/app",
      [
        "expo-build-properties",
        {
          "ios": {
            "useFrameworks": "static"
          },
          "android": {
            "extraProguardRules": "-keep class com.google.android.gms.internal.consent_sdk.** { *; }"
          }
        }
      ],
      "react-native-kochava-tracker/expo-kochava",
      [
        "react-native-google-mobile-ads",
        {
          "androidAppId": "ANDROID_APP_ID",
          "iosAppId": "IOS_APP_ID",
          "userTrackingUsageDescription": "USER_TRACKING_USAGE_DESCRIPTION",
          "skAdNetworkItems": [
            "cstr6suwn9.skadnetwork",
            "4fzdc2evr5.skadnetwork",
            "2fnua5tdw4.skadnetwork",
            "ydx93a7ass.skadnetwork",
            "p78axxw29g.skadnetwork",
            "v72qych5uu.skadnetwork",
            "ludvb6z3bs.skadnetwork",
            "cp8zw746q7.skadnetwork",
            "3sh42y64q3.skadnetwork",
            "c6k4g5qg8m.skadnetwork",
            "s39g8k73mm.skadnetwork",
            "3qy4746246.skadnetwork",
            "f38h382jlk.skadnetwork",
            "hs6bdukanm.skadnetwork",
            "mlmmfzh3r3.skadnetwork",
            "v4nxqhlyqp.skadnetwork",
            "wzmmz9fp6w.skadnetwork",
            "su67r6k2v3.skadnetwork",
            "yclnxrl5pm.skadnetwork",
            "t38b2kh725.skadnetwork",
            "7ug5zh24hu.skadnetwork",
            "gta9lk7p23.skadnetwork",
            "vutu7akeur.skadnetwork",
            "y5ghdn5j9k.skadnetwork",
            "v9wttpbfk9.skadnetwork",
            "n38lu8286q.skadnetwork",
            "47vhws6wlr.skadnetwork",
            "kbd757ywx3.skadnetwork",
            "9t245vhmpl.skadnetwork",
            "a2p9lx4jpn.skadnetwork",
            "22mmun2rn5.skadnetwork",
            "44jx6755aq.skadnetwork",
            "k674qkevps.skadnetwork",
            "4468km3ulz.skadnetwork",
            "2u9pt9hc89.skadnetwork",
            "8s468mfl3y.skadnetwork",
            "klf5c3l5u5.skadnetwork",
            "ppxm28t8ap.skadnetwork",
            "kbmxgpxpgc.skadnetwork",
            "uw77j35x4d.skadnetwork",
            "578prtvx9j.skadnetwork",
            "4dzt52r2t5.skadnetwork",
            "tl55sbb4fm.skadnetwork",
            "c3frkrj4fj.skadnetwork",
            "e5fvkxwrpn.skadnetwork",
            "8c4e2ghe7u.skadnetwork",
            "3rd42ekr43.skadnetwork",
            "97r2b46745.skadnetwork",
            "3qcr597p9d.skadnetwork"
          ]
        }
      ]
    ],
    "extra": {
      "oneSignalAppId": "ONE_SIGNAL_APP_ID"
    }
  }
}
```

### ios/Podfile

```Ruby

```

### android/build.gradle

```Groovy

```

### android/app/build.gradle

```Groovy

```

### android/settings.gradle

```Groovy

```

### AndroidManifest.xml

```XML
<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools">
  <uses-permission android:name="android.permission.INTERNET"/>
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
  <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
  <uses-permission android:name="android.permission.VIBRATE"/>
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
  <uses-permission android:name="com.google.android.gms.permission.AD_ID"/>
  <queries>
    <intent>
      <action android:name="android.intent.action.VIEW"/>
      <category android:name="android.intent.category.BROWSABLE"/>
      <data android:scheme="https"/>
    </intent>
  </queries>
  <application android:name=".MainApplication" android:label="@string/app_name" android:icon="@mipmap/ic_launcher" android:roundIcon="@mipmap/ic_launcher_round" android:allowBackup="true" android:theme="@style/AppTheme" android:supportsRtl="true">
    <meta-data android:name="com.facebook.sdk.AdvertiserIDCollectionEnabled" android:value="false"/>
    <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
    <meta-data android:name="com.facebook.sdk.ApplicationName" android:value="appname"/>
    <meta-data android:name="com.facebook.sdk.AutoInitEnabled" android:value="true"/>
    <meta-data android:name="com.facebook.sdk.AutoLogAppEventsEnabled" android:value="true"/>
    <meta-data android:name="com.facebook.sdk.ClientToken" android:value="@string/facebook_client_token"/>
    <meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="ca-app-pub-1016906836107259~3511685507" tools:replace="android:value"/>
    <meta-data android:name="com.google.android.gms.ads.flag.OPTIMIZE_AD_LOADING" android:value="true" tools:replace="android:value"/>
    <meta-data android:name="com.google.android.gms.ads.flag.OPTIMIZE_AD_LOADING" android:value="true" tools:replace="android:value"/>
    <meta-data android:name="com.google.android.gms.ads.flag.OPTIMIZE_INITIALIZATION" android:value="true" tools:replace="android:value"/>
    <meta-data android:name="com.google.android.gms.ads.flag.OPTIMIZE_AD_LOADING" android:value="true" tools:replace="android:value"/>
    <meta-data android:name="com.google.android.gms.ads.flag.OPTIMIZE_AD_LOADING" android:value="true" tools:replace="android:value"/>
    <meta-data android:name="com.google.android.gms.ads.flag.OPTIMIZE_AD_LOADING" android:value="true" tools:replace="android:value"/>
    <meta-data android:name="com.google.android.gms.ads.flag.OPTIMIZE_AD_LOADING" android:value="true" tools:replace="android:value"/>
    <meta-data android:name="com.google.android.gms.ads.flag.OPTIMIZE_AD_LOADING" android:value="true" tools:replace="android:value"/>
    <meta-data android:name="com.google.android.gms.ads.flag.OPTIMIZE_AD_LOADING" android:value="true" tools:replace="android:value"/>
    <meta-data android:name="com.google.android.gms.ads.flag.OPTIMIZE_AD_LOADING" android:value="true" tools:replace="android:value"/>
    <meta-data android:name="com.google.android.gms.ads.flag.OPTIMIZE_AD_LOADING" android:value="true" tools:replace="android:value"/>
    <meta-data android:name="com.google.android.gms.ads.flag.OPTIMIZE_AD_LOADING" android:value="true" tools:replace="android:value"/>
    <meta-data android:name="com.google.android.gms.ads.flag.OPTIMIZE_INITIALIZATION" android:value="true" tools:replace="android:value"/>
    <meta-data android:name="com.google.android.gms.ads.flag.OPTIMIZE_INITIALIZATION" android:value="true" tools:replace="android:value"/>
    <meta-data android:name="com.google.android.gms.ads.flag.OPTIMIZE_INITIALIZATION" android:value="true" tools:replace="android:value"/>
    <meta-data android:name="com.google.android.gms.ads.flag.OPTIMIZE_INITIALIZATION" android:value="true" tools:replace="android:value"/>
    <meta-data android:name="com.google.android.gms.ads.flag.OPTIMIZE_INITIALIZATION" android:value="true" tools:replace="android:value"/>
    <meta-data android:name="com.google.android.gms.ads.flag.OPTIMIZE_INITIALIZATION" android:value="true" tools:replace="android:value"/>
    <meta-data android:name="com.google.android.gms.ads.flag.OPTIMIZE_INITIALIZATION" android:value="true" tools:replace="android:value"/>
    <meta-data android:name="com.google.android.gms.ads.flag.OPTIMIZE_INITIALIZATION" android:value="true" tools:replace="android:value"/>
    <meta-data android:name="com.google.android.gms.ads.flag.OPTIMIZE_INITIALIZATION" android:value="true" tools:replace="android:value"/>
    <meta-data android:name="expo.modules.notifications.default_notification_color" android:resource="@color/notification_icon_color"/>
    <meta-data android:name="expo.modules.notifications.default_notification_icon" android:resource="@drawable/notification_icon"/>
    <meta-data android:name="expo.modules.updates.ENABLED" android:value="false"/>
    <meta-data android:name="expo.modules.updates.EXPO_UPDATES_CHECK_ON_LAUNCH" android:value="ALWAYS"/>
    <meta-data android:name="expo.modules.updates.EXPO_UPDATES_LAUNCH_WAIT_MS" android:value="0"/>
    <activity android:name=".MainActivity" android:configChanges="keyboard|keyboardHidden|orientation|screenSize|screenLayout|uiMode" android:launchMode="singleTask" android:windowSoftInputMode="adjustResize" android:theme="@style/Theme.App.SplashScreen" android:exported="true" android:screenOrientation="portrait">
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
      <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:scheme="appname"/>
        <data android:scheme="pl.appname.appname"/>
      </intent-filter>
    </activity>
    <activity android:name="com.facebook.FacebookActivity" android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation" android:label="@string/app_name"/>
    <activity android:name="com.facebook.CustomTabActivity" android:exported="true">
      <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:scheme="@string/fb_login_protocol_scheme"/>
      </intent-filter>
    </activity>
  </application>
</manifest>
```

### PR DESCRIPTION
**Pull request by DoctorJohn**
### Description

This PR makes the expo config plugin idempotent (i.e., `npx expo prebuild` can now be run idempotent without duplicate values ending up in any manifests).

### Related issues

- Fixes #747 
- Closes #750 

### Checklist

- I read the [Contributor Guide](https://github.com/invertase/react-native-google-mobile-ads/blob/main/CONTRIBUTING.md)
  and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [x] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `__tests__e2e__`
  - [x] `jest` tests added or updated in `__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

- I added new snapshot tests and carefully reviewed them
- While the issue prompting this PR was focused on Android, I also added a test making sure the plugin behaves as expected regarding Info.plist modifications

:fire:

### CODE REVIEW

File: plugin/src/index.ts [hunk 1]
```diff
@@ -33,7 +33,18 @@ function addReplacingMainApplicationMetaDataItem(
...
+
+  const existingItem = mainApplication['meta-data'].find(
+    item =>
+      item.$['android:name'] === itemName &&
+      item.$['android:value'] === itemValue &&
+      item.$['tools:replace' as keyof AndroidConfig.Manifest.ManifestMetaData['$']] ===
+        'android:value',
+  );
+
+  if (!existingItem) {
```
Comment (dylancom) [inline plugin/src/index.ts:45]: If it exists, we should update it with the latest value i think?

**Review by dylancom — CHANGES_REQUESTED** [review]

File: plugin/src/index.ts (hunk 1 above)
Comment (DoctorJohn) [reply plugin/src/index.ts]: I thought about it for a little, and yes, overwriting values put into the manifest by hand or other config plugins sounds reasonable. I updated the PR.
