### PR TITLE
fix(android banner): debug menu opening

### LINKED ISSUE #188: [🐛] [Android] Can not create dialog without Activity Context
## Issue

Hello Everyone,

I'm experiencing an issue when I'm trying to open Creative Preview & Delivery Inspector using react-native-google-mobile-ads. It's being said here (https://support.google.com/admanager/answer/7180401) that using a gesture (touch and hold the ad with two fingers) I'll be able to open debug mode. Instead, nothing happens. I was able to read this message from Logcat:

`I/Ads: Can not create dialog without Activity Context`

Does someone know why is this happening? Is this even related to library itself? I'm using latest version.

I would be grateful for your help. If any additional informations are needed, please inform.

React Native 0.65.1
react-native-google-mobile-ads: 7.0.1 (but I also checked od ^6 and ^5)
targetSDK: 30
Component: GAMBannerAd (but same behavior with BannerAd)

Best regards.

**EDIT**
I tried `react-native-ad-manager` and same ads respond to this touch so I'm pretty sure it's related to the library now.

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both

</p>
</details>

---

- 👉 Check out [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

### PR DESCRIPTION
**Pull request by aidan-24com**
### Description

unable to open the Ad Debug Menu via gesture on Android. This PR fixes that

### Related issues

Fixes #188 

### Checklist

- I read the [Contributor Guide](https://github.com/invertase/react-native-google-mobile-ads/blob/main/CONTRIBUTING.md)
  and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [ ] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `__tests__e2e__`
  - [ ] `jest` tests added or updated in `__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

Current release (10.0.0) unable to use two finger long press gesture to access debug menu on Android

With this PR, using the gesture activates the menu correctly.

iOS unaffected.

---

🔥

### CODE REVIEW

File: android/src/main/java/io/invertase/googlemobileads/common/ReactNativeAdView.java [hunk 1]
```diff
@@ -13,9 +13,11 @@ public class ReactNativeAdView extends ReactViewGroup {
   private boolean manualImpressionsEnabled;
   private boolean propsChanged;
   private boolean isFluid;
+  private ThemedReactContext reactContext;
 
-  public ReactNativeAdView(final Context context) {
-    super(context);
+  public ReactNativeAdView(final ThemedReactContext context) {
+    super(context.getCurrentActivity());
```
Comment (aidan-24com) [inline android/src/main/java/io/invertase/googlemobileads/common/ReactNativeAdView.java:19]: using the activity context here fixes the LogCat info message `I/Ads: Can not create dialog without Activity Context` & also makes the gesture work

**Comment by aidan-24com** [comment]
@mikehardy the constructor of the view instance uses the `ThemedReactContext`

```java
public ReactNativeAdView createViewInstance(@Nonnull ThemedReactContext themedReactContext) {
  return new ReactNativeAdView(themedReactContext);
}
```

**Review by dylancom — APPROVED** [review]
